server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        # 访问地址
        # http://config-3344.com:3344/master/config-dev.yml
        # http://server:port/{分支名}/{application}-{label}.yml
        # http://server:port/{application}-{label}.yml
        # http://server:port/{application}/{label}/{分支名} //返回JSON
        git:
          uri: https://github.com/takooya/cloud2020.git
          ### 搜索目录
          search-paths:
            - cloud-config/
      ### 读取分支
      label: master
#rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'