server:
  port: 7002

spring:
  application:
    name: cloud-eureka-service

eureka:
  instance:
    hostname: eureka7002.com
  client:
    #    false表示不向注册中心注册自己
    register-with-eureka: false
    #    false表示自己就是注册中心，我的职责就是维护服务，并不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/