server:
  port: 8001

spring:
  application:
    #    Euraka会使用这个名字,一般不要改变
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://rm-2ze39mz4240wb6e5sqo.mysql.rds.aliyuncs.com:3306/atguigu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: takooya
    password: Linze5558
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1 #采样率 1为全部采集

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

eureka:
  client:
    #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    register-with-eureka: true
    #是否从服务端抓取已有的注册信息
    fetch-registry: true
    service-url:
      #      单机Eureka配置
      defaultZone: http://localhost:7001/eureka/
  #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment${server.port}
    prefer-ip-address: true  #访问路径可以显示IP地址
#    lease-renewal-interval-in-seconds: 1  #向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-expiration-duration-in-seconds: 2 #收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除