server:
  port: 9527
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #      开启从注册中心动态创建路由的功能，利用微服务名进行路由
      #      discovery:
      #        locator:
      #          enabled: true
      routes:
        - id: payment_routh #        路由ID，没有规则，但是要求唯一
          uri: http://localhost:8001 #          匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #            断言，路径匹配的进行路由
            - After=2020-05-28T06:08:21.338+08:00[Asia/Shanghai]
        - id: payment_routh2 #        路由ID，没有规则，但是要求唯一
          uri: http://localhost:8001 #          匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #            断言，路径匹配的进行路由
            - Cookie=username, takooya
            - Header=X-Request-Id, \d+
  devtools:
    restart:
      enabled: false