POST http://localhost:8001/payment/create
Content-Type: application/json

{
  "serial": "test003"
}

###
GET http://localhost:8001/payment/get/1

###
GET http://localhost:8001/payment/discovery

###
GET http://localhost:8001/payment/feign/timeout

###

